export function browserPage():string{return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>The Witness — Microphone</title><style>body{font:18px system-ui;background:#101820;color:#edf2f7;max-width:680px;margin:60px auto;padding:24px}input,button{font:inherit;padding:12px;margin:8px 0}button{cursor:pointer}p{line-height:1.6}</style><h1>Record your microphone</h1><p>Send a separate microphone track to the current Witness session. Headphones prevent echo. Use HTTPS and keep this page open while recording.</p><label>Your name <input id="name" maxlength="80" value="Guest"></label><br><button id="start">Start microphone</button><button id="stop" disabled>Stop</button><p id="status" role="status">Microphone is off.</p><script>
let context,stream,socket,worklet;const status=document.querySelector('#status'),start=document.querySelector('#start'),stop=document.querySelector('#stop');
async function finish(){if(worklet)worklet.disconnect();if(stream)stream.getTracks().forEach(track=>track.stop());if(context)await context.close().catch(()=>{});if(socket&&socket.readyState<2)socket.close();context=stream=worklet=null;start.disabled=false;stop.disabled=true;}
start.onclick=async()=>{start.disabled=true;try{
 stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true},video:false});context=new AudioContext({sampleRate:48000});if(context.sampleRate!==48000)throw Error('This browser cannot record at 48 kHz.');
 const url=new URL(location.href);const guestKey='witness-guest:'+url.pathname;let guest=sessionStorage.getItem(guestKey);if(!/^[a-f0-9]{32}$/.test(guest||'')){guest=[...crypto.getRandomValues(new Uint8Array(16))].map(byte=>byte.toString(16).padStart(2,'0')).join('');sessionStorage.setItem(guestKey,guest);}url.searchParams.set('guest',guest);url.protocol=location.protocol==='https:'?'wss:':'ws:';url.searchParams.set('name',document.querySelector('#name').value.trim()||'Guest');socket=new WebSocket(url);socket.binaryType='arraybuffer';
 await new Promise((resolve,reject)=>{socket.onopen=resolve;socket.onerror=()=>reject(Error('Microphone connection failed.'));socket.onclose=()=>reject(Error('Recording session is no longer available.'));});
 socket.onclose=()=>{status.textContent='Microphone connection closed. Your saved audio remains in the session.';finish();};socket.onerror=()=>{status.textContent='Connection error. Restart microphone recording.';finish();};
 const code=\`class Capture extends AudioWorkletProcessor{constructor(){super();this.samples=[];this.timestamp=0;}process(inputs){const channel=inputs[0]?.[0];if(channel){for(const value of channel){this.samples.push(value);if(this.samples.length===960){const bytes=new ArrayBuffer(1924),view=new DataView(bytes);view.setUint32(0,this.timestamp,true);for(let i=0;i<960;i++)view.setInt16(4+i*2,Math.max(-32768,Math.min(32767,Math.round(this.samples[i]*32767))),true);this.port.postMessage(bytes,[bytes]);this.timestamp=(this.timestamp+960)>>>0;this.samples=[];}}}return true;}}registerProcessor('capture',Capture);\`;
 const blob=URL.createObjectURL(new Blob([code],{type:'text/javascript'}));try{await context.audioWorklet.addModule(blob);}finally{URL.revokeObjectURL(blob);}worklet=new AudioWorkletNode(context,'capture');worklet.port.onmessage=event=>{if(socket.readyState===1){if(socket.bufferedAmount>1024*1024){status.textContent='Network is too slow. Microphone recording stopped.';finish();}else socket.send(event.data);}};context.createMediaStreamSource(stream).connect(worklet);worklet.connect(context.destination);await context.resume();stop.disabled=false;status.textContent='Recording microphone into the Witness session.';
 }catch(error){status.textContent=error.message;await finish();}};stop.onclick=async()=>{status.textContent='Microphone stopped. Your track is saved in the session.';await finish();};window.addEventListener('pagehide',()=>{if(stream)stream.getTracks().forEach(track=>track.stop());if(socket)socket.close();});
</script></html>`;}
