export const legalLinks = '<nav aria-label="Policies"><a href="/terms">Terms of Service</a> · <a href="/privacy">Privacy Policy</a></nav>';
const contact = '<p>For the official hosted service, contact Steve (Straconis), the project owner, at <!--email_off--><a href="mailto:support@thewitness.dev">support@thewitness.dev</a><!--/email_off-->. For a self-hosted instance, contact its operator. Do not post recordings, transcripts, private download links, or other personal information publicly.</p>';
const terms = `
<h2>1. Service and scope</h2><p>The Witness is a Discord voice-recording service with separate speaker tracks, audio exports and mixdowns, optional transcripts, and downloadable session archives. Steve (Straconis) operates the official hosted bot and website at thewitness.dev. You may instead run the available source code yourself. A self-hosted instance is operated by its own administrator; Steve does not operate or control that instance. The software license is separate from these hosted-service terms. The Witness is an independent project and is not operated by or affiliated with Discord.</p>
<h2>2. Eligibility and agreement</h2><p>By using the official hosted service, you agree to these terms and acknowledge the <a href="/privacy">Privacy Policy</a>. You must meet Discord’s minimum age requirements (at least 13, or the higher minimum required where you live) and follow applicable laws and <a href="https://discord.com/terms">Discord’s Terms</a> and <a href="https://discord.com/guidelines">Community Guidelines</a>.</p>
<h2>3. Recording notice and permission</h2><p>Before recording, enabling automatic recording, transcribing, or sharing a session, the person configuring or using the bot must clearly inform all participants and obtain the permissions and consents required by applicable law. This includes participants who join later and anyone captured through an optional browser microphone. Explain who will receive the recording and whether transcription or external uploads will be used. A bot’s presence, recording indicator, or acceptance of these terms does not replace participant consent. Do not record secretly or continue recording someone who has objected without a lawful basis.</p>
<h2>4. Your content and responsibilities</h2><p>You retain your rights in your content. You authorize the hosted operator to receive, store, process, and deliver it as needed to provide requested recording, export, transcription, and deletion functions. Only record or upload content you have permission to use, including server intros. Do not use the service for harassment, unlawful surveillance, exploitation, or other illegal activity. Do not collect protected health, financial, or other sensitive information through the bot contrary to Discord’s policies. Do not bypass access controls, misuse someone else’s private links, or interfere with the service.</p>
<h2>5. Access, sharing, and deletion</h2><p>Signed recording, dashboard, export, and browser links are bearer links: anyone who obtains a valid link can use the functions it grants without a separate Discord login. Keep them private and share only with authorized people. An expired link does not mean the underlying recording was deleted. Server members with Manage Server permission can use the bot’s delete command to remove a stopped session and its local exports. See the Privacy Policy for retention and copies outside the service.</p>
<h2>6. Availability and accuracy</h2><p>The service is in active development. Recording, recovery, exports, and transcription may fail or produce incomplete or inaccurate results. Review transcripts before relying on them and keep your own copies of important files. No uninterrupted availability, permanent storage, or particular transcription accuracy is promised. The operator may change, limit, suspend, or discontinue access for maintenance, capacity, abuse, or other operational reasons.</p>
<h2>7. Limitations</h2><p>To the extent permitted by applicable law, the service is provided “as is” and “as available,” without warranties of fitness, reliability, or suitability for a particular purpose. To that extent, the operator is not responsible for losses caused by unavailable service, lost recordings, inaccurate transcripts, or your unauthorized recording or sharing. Nothing in these terms excludes rights or liabilities that cannot lawfully be excluded.</p>
<h2>8. Self-hosting</h2><p>Self-hosted operators are responsible for their deployment, participant notices, permissions, security, storage, retention, integrations, and their own applicable terms and privacy information. These pages describe the official service; they do not promise how an independent instance behaves. Use the source under its included license.</p>
<h2>9. Changes and contact</h2><p>Updates will appear here with a revised effective date. Review changes before future use; changes do not authorize new uses of previously collected recordings without any permission required by law. Report misuse or service concerns using the contact options below.</p>${contact}`;
const privacy = `
<h2>1. Who operates your instance</h2><p>This policy describes the official The Witness bot and thewitness.dev, operated by Steve (Straconis). For self-hosted deployments, the person or organization running the instance controls its processing and storage. Using the published source does not itself send your self-hosted recordings to Steve or the official service. Ask that instance’s operator for its privacy information.</p>
<h2>2. Information processed</h2><ul><li>Voice audio received while a session is recording, saved in separate speaker tracks; optional browser microphone audio when a participant uses a capture link.</li><li>Discord user IDs and usernames associated with tracks; server and channel IDs, channel names, session IDs, start/end times, recording state, and technical track information.</li><li>Session titles, shared notes and markers, server settings and recording schedules, and uploaded audio intros when those features are used.</li><li>Requested exports, mixdowns, editing information, transcripts (TXT, SRT, VTT), archives, and export-job status or errors.</li><li>Technical connection information needed to serve web requests, including IP addresses handled by the web server and hosting network. Operational and error logs may contain session identifiers and technical errors.</li></ul><p>The recording feature captures audio rather than Discord video or screen sharing. It is not designed to archive general Discord text-channel conversations.</p>
<h2>3. Purposes and recording controls</h2><p>We process this information to record sessions requested or configured by server users, generate and deliver exports and transcripts, maintain settings, recover interrupted sessions, diagnose failures, protect the service, and carry out deletion. Optional audio/video sync saves a generated cue track, cue IDs, and timing markers. When you pair VTT Cameraman using a private read-only link, it receives session/cue IDs and timing to produce its flash and beep; that feed does not deliver voice recordings. Automatic recording can be enabled through server settings, schedules, or event rules. The person enabling it must notify participants and obtain the required consent; the software does not collect an individual consent response from every speaker. If you do not want to be recorded, tell the organizer and avoid speaking in a channel while recording is active. Leaving stops future capture of your voice through that connection but does not erase audio already saved.</p>
<h2>4. Official hosted storage and processing</h2><p>Official recordings and generated files are stored on the operator’s RackNerd VPS. Transcription is optional and currently runs locally on that server using whisper.cpp and a configured model; it is not sent to a hosted transcription API by the current configuration. Transcripts may contain errors and sensitive details spoken in the session. The current deployment has no connected cloud-upload accounts. If an external upload integration is later enabled and selected, the selected files will also be processed and stored by that provider under its own policies. Self-hosted operators can change executables, models, hosting, and integrations, so these official-hosted details do not apply automatically to them.</p>
<h2>5. Access and sharing</h2><p>The hosted operator and people administering the host can access stored files for service operation and support. Discord carries bot commands, recording notices, and responses; exports delivered as Discord attachments are also stored by Discord. People receiving downloaded files or valid signed links can access the content. A signed link is not tied to a particular Discord account: anyone holding it can use the access it grants, including export or dashboard actions where available. Links normally expire after 24 hours, but new links can be issued while files remain stored. Keep links and downloaded archives private.</p><p>RackNerd provides the VPS, and Cloudflare fronts the public website. These providers process infrastructure and network data needed to host and deliver the service; Cloudflare also supplies network-error reporting headers, so browsers may send connection diagnostics to Cloudflare. We may disclose information when legally required or necessary to address security or abuse. The application has no advertising, data-sale, or model-training workflow. These pages load no third-party analytics or tracking resources and set no cookies. The current website configuration disables routine web access logs; error and application logs can still be produced. This is not a promise of anonymous use or end-to-end encryption of stored recordings.</p>
<h2>6. Retention and deletion</h2><p>There is no fixed automatic deletion period enabled in the current hosted configuration. Recordings and exports remain stored until deleted; do not interpret link expiry as a retention deadline or a guarantee of permanent availability. Optional per-server retention can delete completed sessions and their local exports after a configured number of days measured from completion. Its cleanup runs periodically and skips active, failed, interrupted, or busy sessions, so it does not establish a deadline for every file.</p><p>A member with Manage Server permission can stop a recording and use <code>/delete</code> with its session ID and confirmation to remove the session directory, including its audio and local exports. This does not remove downloaded copies, Discord attachments, external uploads, server-wide intros or settings, or all operational/job records. Separate recovery sessions and any independently retained copies need separate attention. Removing the bot from a server does not automatically delete prior recordings. We do not promise immediate erasure from every infrastructure copy or backup.</p>
<h2>7. Requests and concerns</h2><p>To request access, correction, deletion, or assistance with a recording, contact your server administrator or the hosted operator below. Include the server, approximate session date, and session ID if available, and explain your request without sending private audio publicly. We may need to verify your connection to the session and coordinate with its organizer to protect other participants’ information. Privacy rights depend on applicable law; nothing here limits rights that apply to you.</p>${contact}
<h2>8. Policy changes</h2><p>We will update this page and its effective date when the service or its data practices change. Self-hosted operators must explain their own changes to their users.</p>`;
export function legalPage(kind: "terms" | "privacy"): string {
 const title = kind === "terms" ? "Terms of Service" : "Privacy Policy";
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — The Witness</title><meta name="description" content="The Witness ${title}: official hosted Discord voice recording and self-hosted deployments."><style>
*{box-sizing:border-box}body{margin:0;background:#090a0b;color:#eeeef0;font:16px system-ui;line-height:1.7}body:before{content:"";position:fixed;z-index:-1;inset:0;background:radial-gradient(ellipse at 15% 40%,#07322e88,transparent 55%),radial-gradient(ellipse at 90% 80%,#07322e55,transparent 55%)}.page{max-width:840px;margin:auto;padding:24px}header{display:flex;align-items:center;gap:12px;margin-bottom:20px;font-size:28px;font-weight:750}.mark{display:grid;place-items:center;background:#0b403a;border:1px solid #00b8a4;border-radius:9px;width:40px;height:40px;font-size:23px}.card{background:#19191d;padding:28px;border-radius:16px;margin:24px 0;box-shadow:0 2px 8px #0003}h1{font-size:30px;line-height:1.25;margin:0}h2{font-size:21px;line-height:1.4;margin:30px 0 10px}p{margin:12px 0}a{color:#00d0b9;text-underline-offset:3px}a:focus-visible{outline:2px solid #fff;outline-offset:4px}.muted,footer{color:#b5b6c1}footer{font-size:14px;padding-bottom:24px}li{margin:8px 0}code{overflow-wrap:anywhere}@media(max-width:480px){.page{padding:16px}.card{padding:18px}h1{font-size:26px}}
</style></head><body><div class="page"><header><span class="mark" aria-hidden="true">◉</span>The Witness</header>${legalLinks}<main class="card"><h1>${title}</h1><p class="muted">Effective October 2, 2026</p>${kind === "terms" ? terms : privacy}</main><footer>Official hosted bot or self-hosted — your choice. ${legalLinks}</footer></div></body></html>`;
}
