const test=require('node:test'),assert=require('node:assert/strict');const {mkdtemp,rm}=require('node:fs/promises');const os=require('node:os'),path=require('node:path');const {mayUseBot}=require('../dist/discord/access');const {SettingsStore}=require('../dist/storage/settings');
test('role mode defaults to everyone and fails closed when membership is missing',()=>{assert.equal(mayUseBot({autoJoin:false,autoRecord:false},undefined),true);const restricted={autoJoin:false,autoRecord:false,restrictAccess:true,accessRoleID:'456'};assert.equal(mayUseBot(restricted,['456']),true);assert.equal(mayUseBot(restricted,['789']),false);assert.equal(mayUseBot(restricted,undefined),false);assert.equal(mayUseBot({...restricted,restrictAccess:false},[]),true);});
test('role policy survives restart and invalid or incomplete restrictions do not replace saved settings',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-role-'));try{const file=path.join(root,'settings.json'),settings=new SettingsStore(file);await settings.load();await assert.rejects(settings.update('123',{restrictAccess:true}),/Choose/);await settings.update('123',{restrictAccess:true,accessRoleID:'456'});const restarted=new SettingsStore(file);await restarted.load();assert.equal(mayUseBot(restarted.get('123'),['456']),true);await assert.rejects(restarted.update('123',{accessRoleID:'bad'}),/Invalid/);assert.equal(restarted.get('123').accessRoleID,'456');await restarted.update('123',{restrictAccess:false});assert.equal(mayUseBot(restarted.get('123'),[]),true);}finally{await rm(root,{recursive:true,force:true});}});
test('Discord role policy guards commands, buttons and modal submissions while server managers can change it',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-access-'));process.env.DISCORD_TOKEN='offline-test-token';process.env.RECORDING_PATH=root;const {EventEmitter}=require('node:events');const {createDiscordClient,recordings,settingsStore,closeRecordingPanels}=require('../dist/discord/client');
 try{await settingsStore.load();const client=createDiscordClient(),guild={id:'123',roles:new Map([['456',{id:'456'}]]),members:new Map(),channels:new Map()};client.guilds.set(guild.id,guild);const voice=new EventEmitter();voice.receive=()=>new EventEmitter();voice.disconnect=()=>{};const session=await recordings.start(guild,'voice',voice);
 async function dispatch(type,data,roles=[],admin=false){let done,timer;const result=new Promise(resolve=>done=resolve),interaction={type,data,guildID:guild.id,member:{id:'member',roles,permissions:{has:()=>admin}},acknowledged:false,defer:async()=>{interaction.acknowledged=true;},createMessage:async body=>done(body),editOriginalMessage:async body=>done(body)};client.emit('interactionCreate',interaction);try{return await Promise.race([result,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('Timeout')),2000))]);}finally{clearTimeout(timer);}}
 const access=(mode,role)=>({name:'access',options:[{name:'mode',value:mode},...(role?[{name:'role',value:role}]:[])]});assert.ok((await dispatch(2,access('role','456'))).content.includes('Manage Server'));assert.equal(settingsStore.get(guild.id).restrictAccess,undefined);assert.ok((await dispatch(2,access('role','456'),[],true)).content.includes('now require'));
 const note={name:'note',options:[{name:'text',value:'Wrangler note'}]};assert.ok((await dispatch(2,note)).content.includes('restricted'));assert.ok((await dispatch(3,{custom_id:`witness:stop:${session.id}`})).content.includes('restricted'));assert.ok((await dispatch(5,{custom_id:`witness:note-submit:${session.id}`,components:[{components:[{custom_id:'note',value:'Denied note'}]}]})).content.includes('restricted'));assert.equal(session.notes,0);assert.equal(session.state,'recording');assert.ok((await dispatch(2,note,['456'])).content.includes('Note saved'));assert.equal(session.notes,1);
 assert.ok((await dispatch(2,access('everyone'),[],true)).content.includes('open to all'));assert.ok((await dispatch(2,note)).content.includes('Note saved'));assert.equal(session.notes,2);
 }finally{await recordings.shutdown();await closeRecordingPanels();await rm(root,{recursive:true,force:true});}
});
