const test=require('node:test'),assert=require('node:assert/strict'),{mkdtemp,readFile,writeFile,rm,stat}=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{createServer}=require('node:http');const {CloudAccounts,providers}=require('../dist/integrations/accounts');
test('owner OAuth uses state/PKCE, consumes callbacks once and persists rotating refresh tokens',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-oauth-')),saved={};let server;try{for(const provider of providers)for(const suffix of ['CLIENT_ID','CLIENT_SECRET']){const key=provider.toUpperCase()+'_'+suffix;saved[key]=process.env[key];process.env[key]='offline-'+suffix;}const calls=[];server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const params=new URLSearchParams(body);calls.push(params);res.setHeader('Content-Type','application/json');res.end(JSON.stringify({access_token:'access-'+calls.length,refresh_token:'rotated-'+calls.length,expires_in:3600}));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const endpoint='http://127.0.0.1:'+server.address().port,overrides=Object.fromEntries(providers.map(provider=>[provider,{token:endpoint}])),accounts=new CloudAccounts(root,overrides);
 for(const provider of providers){const url=new URL(await accounts.connect(provider,'https://witness.example'));assert.equal(url.searchParams.get('redirect_uri'),'https://witness.example/oauth/callback');assert.equal(url.searchParams.get('code_challenge_method'),provider==='box'?null:'S256');const state=url.searchParams.get('state');await assert.rejects(accounts.callback('invalid','code','https://witness.example'));await accounts.callback(state,'code','https://witness.example');await assert.rejects(accounts.callback(state,'code','https://witness.example'));const filename=path.join(root,'private-accounts',provider+'.json'),credentials=JSON.parse(await readFile(filename));assert.equal((await stat(filename)).mode&0o777,0o600);credentials.expiresAt=0;await writeFile(filename,JSON.stringify(credentials));const count=calls.length,tokens=await Promise.all([accounts.token(provider),accounts.token(provider)]);assert.equal(calls.length,count+1);assert.equal(tokens[0],tokens[1]);assert.equal(calls.at(-1).get('refresh_token'),credentials.refreshToken);const restarted=new CloudAccounts(root,overrides);assert.equal(await restarted.token(provider),tokens[0]);const status=(await restarted.status()).find(item=>item.provider===provider);assert.equal(status.connected,true);assert.ok(!JSON.stringify(status).includes('access-'));await restarted.disconnect(provider);assert.equal(await restarted.configured(provider),false);}
 }finally{for(const [key,value] of Object.entries(saved))if(value===undefined)delete process.env[key];else process.env[key]=value;if(server)await new Promise(resolve=>server.close(resolve));await rm(root,{recursive:true,force:true});}});
test('expired and wrong-origin account callbacks fail before contacting a provider',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-expired-oauth-'));const oldID=process.env.BOX_CLIENT_ID,oldSecret=process.env.BOX_CLIENT_SECRET;process.env.BOX_CLIENT_ID='fixture';process.env.BOX_CLIENT_SECRET='fixture';try{const accounts=new CloudAccounts(root);for(const expired of [true,false]){const url=new URL(await accounts.connect('box','https://witness.example')),state=url.searchParams.get('state'),file=path.join(root,'private-accounts','pending-'+state+'.json');if(expired){const pending=JSON.parse(await readFile(file));pending.expiresAt=0;await writeFile(file,JSON.stringify(pending));}await assert.rejects(accounts.callback(state,'code',expired?'https://witness.example':'https://other.example'),/expired|wrong address/);}}finally{if(oldID===undefined)delete process.env.BOX_CLIENT_ID;else process.env.BOX_CLIENT_ID=oldID;if(oldSecret===undefined)delete process.env.BOX_CLIENT_SECRET;else process.env.BOX_CLIENT_SECRET=oldSecret;await rm(root,{recursive:true,force:true});}});
test('separate account instances serialize reconnect against an in-flight refresh',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-account-race-'));const previousID=process.env.BOX_CLIENT_ID,previousSecret=process.env.BOX_CLIENT_SECRET;process.env.BOX_CLIENT_ID='fixture';process.env.BOX_CLIENT_SECRET='fixture';let release;const gate=new Promise(resolve=>release=resolve);let refreshing;const entered=new Promise(resolve=>refreshing=resolve);let token,callback;
 try{const first=new CloudAccounts(root),second=new CloudAccounts(root);const link=new URL(await second.connect('box','https://witness.example'));const file=path.join(root,'private-accounts','box.json');await writeFile(file,JSON.stringify({accessToken:'expired',refreshToken:'old-refresh',expiresAt:0}));
 first.exchange=async()=>{refreshing();await gate;return {accessToken:'refreshed-old-account',refreshToken:'rotated-old-account',expiresAt:Date.now()+3600000};};second.exchange=async()=>({accessToken:'new-account',refreshToken:'new-account-refresh',expiresAt:Date.now()+3600000});
 token=first.token('box');await entered;callback=second.callback(link.searchParams.get('state'),'code','https://witness.example');
 // Let a concurrently completing reconnect finish first in the broken implementation.
 await Promise.race([callback,new Promise(resolve=>setTimeout(resolve,150))]);release();await Promise.all([token,callback]);assert.equal(JSON.parse(await readFile(file)).accessToken,'new-account','A stale refresh must not overwrite a newly connected account');
 }finally{release();await Promise.allSettled([token,callback]);if(previousID===undefined)delete process.env.BOX_CLIENT_ID;else process.env.BOX_CLIENT_ID=previousID;if(previousSecret===undefined)delete process.env.BOX_CLIENT_SECRET;else process.env.BOX_CLIENT_SECRET=previousSecret;await rm(root,{recursive:true,force:true});}
});
test('disconnect on another account instance waits for refresh and leaves credentials removed',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-account-disconnect-'));let release,started;const gate=new Promise(resolve=>release=resolve),entered=new Promise(resolve=>started=resolve);let token,disconnect;
 try{const first=new CloudAccounts(root),second=new CloudAccounts(root);await require('node:fs/promises').mkdir(path.join(root,'private-accounts'));const file=path.join(root,'private-accounts','box.json');await writeFile(file,JSON.stringify({accessToken:'expired',refreshToken:'old',expiresAt:0}));first.exchange=async()=>{started();await gate;return {accessToken:'new',refreshToken:'rotated',expiresAt:Date.now()+3600000};};token=first.token('box');await entered;disconnect=second.disconnect('box');await Promise.race([disconnect,new Promise(resolve=>setTimeout(resolve,150))]);release();await Promise.all([token,disconnect]);await assert.rejects(readFile(file),{code:'ENOENT'});}
 finally{release();await Promise.allSettled([token,disconnect]);await rm(root,{recursive:true,force:true});}
});
