const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{randomUUID}=require('node:crypto');
const {estimateExportBytes,cleanTransientArtifacts,sweepArtifacts,protectRecordingSpace}=require('../dist/exports/storage'),{ExportQueue}=require('../dist/exports/jobs'),{RecordingSession}=require('../dist/recording/session');
const until=async check=>{for(let i=0;i<300;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Timeout');};
async function recording(root){const session=await RecordingSession.create(root,'guild','voice');await session.append(Buffer.from([0xf8,0xff,0xfe]),'user','User',0,1n);await session.close();return session.id;}
const space=(available)=>({availableBytes:available,warningBytes:1000,totalBytes:1e12,low:available<1000,criticalBytes:100,critical:available<100,checkedAt:new Date().toISOString()});
test('project preflight accounts for duplicate audio, mix, full raw originals and edited duration',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-estimate-'));try{const id=await recording(root),file=path.join(root,id,'session.json'),metadata=JSON.parse(await fs.readFile(file));metadata.durationSamples=3*3600*48000;metadata.tracks=Array.from({length:6},(_,i)=>({track:i+1,id:String(i),username:'Speaker'}));await fs.writeFile(file,JSON.stringify(metadata));const job={sessionID:id,guildID:'guild',format:'audacity',mix:false};const bytes=await estimateExportBytes(root,job),pcm=6*10800*192000;assert.ok(bytes>pcm*2);assert.ok(bytes<pcm*3,'Peak stages must not double-count scratch space during ZIP packaging');assert.ok(await estimateExportBytes(root,{...job,mix:true})>bytes);const excerpt={...job,trimEnd:60};assert.ok(await estimateExportBytes(root,{...excerpt,includeRaw:true})>await estimateExportBytes(root,excerpt));const edits={tracks:metadata.tracks.map(t=>({track:t.track,clips:[{start:0,end:60,at:7200}]}))};assert.ok(await estimateExportBytes(root,{...excerpt,edits})>await estimateExportBytes(root,excerpt));}finally{await fs.rm(root,{recursive:true,force:true});}
});
test('insufficient export capacity waits without starting and resumes when space returns',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-disk-admit-'));let queue,free=1000,runs=0;try{const id=await recording(root);queue=new ExportQueue(root,async()=>{runs++;return root;},undefined,1,async()=>space(free));await queue.load();const job=await queue.enqueue(id,'guild','wav');await until(()=>job.stage?.startsWith('Waiting for disk space')&&queue.cooldown&&!queue.dispatching);assert.equal(runs,0);assert.equal(job.state,'queued');assert.equal(queue.position(job.id),1);free=1e12;clearTimeout(queue.cooldown);queue.cooldown=undefined;queue.kick();await until(()=>job.state==='completed');assert.equal(runs,1);}finally{await queue?.close();await fs.rm(root,{recursive:true,force:true});}
});
test('concurrent exports reserve their budgets rather than admitting both against the same free bytes',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-disk-reserve-'));let queue,release;const gate=new Promise(resolve=>release=resolve);let runs=0;try{const a=await recording(root),b=await recording(root),required=await estimateExportBytes(root,{sessionID:a,guildID:'guild',format:'wav',mix:false});queue=new ExportQueue(root,async()=>{runs++;await gate;return root;},undefined,2,async()=>space(required*1.5+1000));await queue.load();const first=await queue.enqueue(a,'guild','wav');await until(()=>runs===1);const second=await queue.enqueue(b,'guild','wav');await until(()=>second.stage?.startsWith('Waiting for disk space'));assert.equal(runs,1);assert.equal(first.state,'running');assert.equal(second.state,'queued');release();}finally{release();await queue?.close();await fs.rm(root,{recursive:true,force:true});}
});
test('disk pressure aborts exports, cleans scratch before requeue, preserves originals and releases reservations',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-disk-pause-'));let queue,created,ready=false;try{const id=await recording(root),original=await fs.readFile(path.join(root,id,'audio.ogg.data'));queue=new ExportQueue(root,async(_root,session,options)=>{created=path.join(root,session,'export-'+randomUUID()+'.tmp');await fs.mkdir(created);await fs.writeFile(path.join(created,'scratch'),'temporary');try{await new Promise((resolve,reject)=>{options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true});ready=true;});}finally{await fs.rm(created,{recursive:true,force:true});}},undefined,1,async()=>space(1e12));await queue.load();const job=await queue.enqueue(id,'guild','wav');await until(()=>ready);await queue.pauseForDisk();assert.equal(job.state,'queued');assert.equal(job.stage,'Waiting for disk space');assert.equal(job.error,undefined);await assert.rejects(fs.stat(created),{code:'ENOENT'});assert.deepEqual(await fs.readFile(path.join(root,id,'audio.ogg.data')),original);assert.equal(queue.active.size,0);await until(()=>queue.reservations.size===0);assert.ok(queue.cooldown,'Disk pause must schedule a retry rather than stick forever');}finally{await queue?.close();await fs.rm(root,{recursive:true,force:true});}
});
test('emergency recording stop occurs only after export cleanup and a fresh critical-space check',async()=>{
 for(const critical of [false,true]){const calls=[];await protectRecordingSpace({pauseForDisk:async()=>calls.push('abort-and-clean')},async()=>{calls.push('fresh-check');return {critical};},async()=>calls.push('stop-recordings'));assert.deepEqual(calls,critical?['abort-and-clean','fresh-check','stop-recordings']:['abort-and-clean','fresh-check']);}
});
test('artifact sweep retains originals, active exports, editor work and source chains; cleans stale uploads/intros',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-artifact-sweep-'));try{const id=await recording(root),parent=path.join(root,id),now=Date.now(),old=new Date(now-72*3600000);async function output(manifest={},editor=false){const name='export-'+randomUUID(),dir=path.join(parent,name);await fs.mkdir(dir);await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify({sessionID:id,tracks:[{file:'track-1.wav',username:'User'}],...manifest}));await fs.writeFile(path.join(dir,'track-1.wav'),'audio');if(editor)await fs.writeFile(path.join(dir,'editor-state.json'),'{}');await fs.utimes(dir,old,old);return name;}
 const expired=await output(),active=await output(),source=await output(),edited=await output({sourceExport:source,edits:{tracks:[]}}),saved=await output({},true);const recent=await output();await fs.utimes(path.join(parent,recent),new Date(),new Date());const introDir=path.join(root,'server-intros','a'.repeat(64));await fs.mkdir(introDir,{recursive:true});const current=randomUUID(),used=randomUUID(),unused=randomUUID();for(const intro of [current,used,unused]){await fs.writeFile(path.join(introDir,intro+'.json'),JSON.stringify({id:intro}));await fs.writeFile(path.join(introDir,intro+'.pcm'),'pcm');await fs.utimes(path.join(introDir,intro+'.json'),old,old);await fs.utimes(path.join(introDir,intro+'.pcm'),old,old);}await fs.writeFile(path.join(introDir,'current.json'),JSON.stringify({id:current}));const abandoned=path.join(introDir,'upload-'+randomUUID());await fs.mkdir(abandoned);await fs.utimes(abandoned,old,old);
 await sweepArtifacts(root,[{sessionID:id,directory:active}],new Set([used]),now);await assert.rejects(fs.stat(path.join(parent,expired)),{code:'ENOENT'});for(const name of [active,source,edited,saved,recent])assert.ok((await fs.stat(path.join(parent,name))).isDirectory());assert.ok((await fs.stat(path.join(parent,'audio.ogg.data'))).size>0);for(const intro of [current,used])await fs.stat(path.join(introDir,intro+'.pcm'));await assert.rejects(fs.stat(path.join(introDir,unused+'.pcm')),{code:'ENOENT'});await assert.rejects(fs.stat(abandoned),{code:'ENOENT'});
 const tmp=path.join(parent,'export-'+randomUUID()+'.tmp'),deleted=path.join(root,'.deleted-'+randomUUID());await fs.mkdir(tmp);await fs.mkdir(deleted);await fs.mkdir(path.join(root,'jobs'));const jsonTmp=path.join(root,'jobs',randomUUID()+'.json.tmp');await fs.writeFile(jsonTmp,'partial');await cleanTransientArtifacts(root);for(const file of [tmp,deleted,jsonTmp])await assert.rejects(fs.stat(file),{code:'ENOENT'});await fs.stat(path.join(parent,'audio.ogg.data'));
 const ambiguous=await recording(root),unknown=path.join(root,ambiguous,'export-'+randomUUID()),protectedDir=path.join(root,ambiguous,'export-'+randomUUID());await fs.mkdir(unknown);await fs.writeFile(path.join(unknown,'manifest.json'),'broken');await fs.mkdir(protectedDir);await fs.writeFile(path.join(protectedDir,'manifest.json'),JSON.stringify({sessionID:ambiguous,tracks:[]}));await fs.utimes(protectedDir,old,old);await sweepArtifacts(root,[],new Set(),now);await fs.stat(protectedDir);await fs.stat(unknown);
 }finally{await fs.rm(root,{recursive:true,force:true});}
});
test('terminal job files older than seven days leave memory while queued jobs stay',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-job-prune-'));let queue;try{queue=new ExportQueue(root,undefined,()=>true);await queue.load();const terminal=randomUUID(),queued=randomUUID();for(const [id,state] of [[terminal,'completed'],[queued,'queued']]){const job={id,sessionID:randomUUID(),guildID:'guild',format:'wav',mix:false,state,createdAt:new Date().toISOString()};queue.jobs.set(id,job);await queue.save(job);const old=new Date(Date.now()-8*86400000);await fs.utimes(path.join(root,'jobs',id+'.json'),old,old);}await queue.maintenance();assert.equal(queue.get(terminal),undefined);assert.equal(queue.get(queued).state,'queued');await assert.rejects(fs.stat(path.join(root,'jobs',terminal+'.json')),{code:'ENOENT'});}finally{await queue?.close();await fs.rm(root,{recursive:true,force:true});}
});
test('one server export hitting the disk guard leaves other server recordings running after scratch is reclaimed',async()=>{
 const {RecordingManager}=require('../dist/recording/manager'),{EventEmitter}=require('node:events');const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-multiguild-disk-')),manager=new RecordingManager(root);let queue,free=1e12,started=false;try{const id=await recording(root);for(const guild of ['a','b']){const voice=new EventEmitter();voice.receive=()=>new EventEmitter();const session=await manager.start({id:guild,members:new Map()},'voice',voice);await session.append(Buffer.from([0xf8,0xff,0xfe]),'user','User');}queue=new ExportQueue(root,async(_root,_id,options)=>{started=true;try{await new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(options.signal.reason),{once:true}));}finally{free=1e12;}},undefined,1,async()=>space(free));await queue.load();const job=await queue.enqueue(id,'guild','wav');await until(()=>started);free=10;await protectRecordingSpace(queue,async()=>space(free),()=>manager.stopForLowDisk());assert.equal(job.state,'queued');assert.equal(manager.sessions.size,2);for(const session of manager.sessions.values()){assert.equal(session.state,'recording');assert.equal(session.packets,1);}}finally{await queue?.close();await manager.shutdown();await fs.rm(root,{recursive:true,force:true});}
});
test('loading saved jobs can defer all exporters until recovery and monitoring are ready',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-deferred-queue-'));let queue,runs=0;try{const id=await recording(root);queue=new ExportQueue(root,async()=>{runs++;return root;});await queue.load(false);const job=await queue.enqueue(id,'guild','wav');await new Promise(resolve=>setTimeout(resolve,30));assert.equal(runs,0);assert.equal(job.state,'queued');queue.start();await until(()=>job.state==='completed');assert.equal(runs,1);}finally{await queue?.close();await fs.rm(root,{recursive:true,force:true});}
});
test('a deployment marker arriving during an export capacity check prevents a late submission',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-late-export-'));let queue,enter,release;const entered=new Promise(resolve=>enter=resolve),gate=new Promise(resolve=>release=resolve);try{const id=await recording(root);queue=new ExportQueue(root,undefined,async()=>{enter();await gate;return false;});await queue.load(false);const submitting=queue.enqueue(id,'guild','wav');await entered;await fs.writeFile(path.join(root,'.deploy-pending'),'pending');release();await assert.rejects(submitting,/update is being prepared/);assert.equal(queue.jobs.size,0);}finally{release();await queue?.close();await fs.rm(root,{recursive:true,force:true});}
});
test('a deployment marker arriving during recording admission prevents capture from starting',async()=>{
 const {RecordingManager}=require('../dist/recording/manager'),{EventEmitter}=require('node:events');const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-late-record-'));let enter,release;const entered=new Promise(resolve=>enter=resolve),gate=new Promise(resolve=>release=resolve),manager=new RecordingManager(root,[],undefined,async()=>{enter();await gate;return false;});try{const voice=new EventEmitter();voice.receive=()=>new EventEmitter();const starting=manager.start({id:'guild',members:new Map()},'voice',voice);await entered;await fs.writeFile(path.join(root,'.deploy-pending'),'pending');release();await assert.rejects(starting,/update is being prepared/);assert.equal(manager.sessions.size,0);assert.deepEqual((await fs.readdir(root)).filter(name=>!name.startsWith('.')),[]);}finally{release();await manager.shutdown();await fs.rm(root,{recursive:true,force:true});}
});
test('idle deployment permits durable disk-waiting jobs but still rejects recording or active export work',async()=>{
 const {spawnSync}=require('node:child_process');const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-idle-disk-'));try{await fs.mkdir(path.join(root,'dist'));await fs.writeFile(path.join(root,'dist','config.js'),'exports.config='+JSON.stringify({recordingPath:root}));await fs.mkdir(path.join(root,'jobs'));const file=path.join(root,'jobs',randomUUID()+'.json'),script=path.resolve(__dirname,'../scripts/deploy-idle.cjs');const check=()=>spawnSync(process.execPath,[script],{cwd:root}).status;await fs.writeFile(file,JSON.stringify({state:'queued',stage:'Waiting for disk space'}));assert.equal(check(),0);for(const state of ['running','cancelling']){await fs.writeFile(file,JSON.stringify({state,stage:'Waiting for disk space'}));assert.equal(check(),1);}await fs.writeFile(file,JSON.stringify({state:'queued',stage:'Waiting to retry'}));assert.equal(check(),1);await fs.writeFile(file,JSON.stringify({state:'queued',stage:'Waiting for disk space'}));const session=path.join(root,randomUUID());await fs.mkdir(session);await fs.writeFile(path.join(session,'session.json'),JSON.stringify({state:'recording'}));assert.equal(check(),1);}finally{await fs.rm(root,{recursive:true,force:true});}
});
