const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path'),{EventEmitter,once}=require('node:events'),{WebSocket}=require('ws'),vm=require('node:vm');
const {RecordingManager}=require('../dist/recording/manager'),{RecordingSession}=require('../dist/recording/session'),{SettingsStore}=require('../dist/storage/settings'),{DownloadService}=require('../dist/downloads/service');
const until=async predicate=>{for(let i=0;i<300;i++){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Timeout');};
function connection(){const voice=new EventEmitter();voice.receive=()=>new EventEmitter();voice.disconnect=()=>{};return voice;}
test('clean voice disconnect saves without reconnecting; error disconnect still retries',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-clean-disconnect-')),manager=new RecordingManager(root,[0]);try{let attempts=0,notified=0;manager.onDisconnected=async()=>notified++;const voice=connection(),session=await manager.start({id:'clean',members:new Map()},'voice',voice,async()=>{attempts++;return connection();});await session.append(Buffer.from([0xf8,0xff,0xfe]),'user','User');manager.syncSessions.set('clean',{stop:async emit=>assert.equal(emit,false,'Forced disconnect must not delay finalization for an end cue')});voice.emit('disconnect');await until(()=>!manager.sessions.has('clean'));assert.equal(attempts,0);assert.equal(notified,1);assert.equal(session.state,'completed');assert.equal(session.stopReason,'disconnected');const broken=connection(),retry=await manager.start({id:'retry',members:new Map()},'voice',broken,async()=>{attempts++;return connection();});broken.emit('disconnect',Error('Network lost'));await until(()=>attempts===1&&retry.voiceState==='connected');assert.equal(retry.state,'recording');}finally{await manager.shutdown();await fs.rm(root,{recursive:true,force:true});}
});
test('dashboard settings and intro upload require an untampered manager capability; recording links cannot replace intros',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-dashboard-manager-'));let service;try{const settings=new SettingsStore(path.join(root,'settings.json')),session=await RecordingSession.create(root,'guild','voice');await session.append(Buffer.from([0xf8,0xff,0xfe]),'user','User');await session.close();service=await DownloadService.create(root,'http://localhost');service.attach({},settings,{sessions:new Map()});const port=await service.listen(0,'127.0.0.1'),local=url=>url.replace('http://localhost',`http://127.0.0.1:${port}`),read=local(service.dashboardLink('guild')),manager=local(service.dashboardLink('guild',true));const post=async(url,body)=>{const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await response.text();return response.status;};const change={action:'settings',autoJoin:true,autoRecord:true};assert.equal(await post(read,change),403);assert.equal(await post(read+'&manager=1',change),403);assert.equal(await post(manager.replace('&manager=1',''),change),403);assert.equal(await post(manager,change),200);assert.equal(settings.get('guild').autoRecord,true);assert.equal(await post(read,{action:'upload-intro'}),403);assert.equal(await post(local(service.recordingLink(session.id)),{action:'upload-intro'}),403);
 for(const url of [read,manager,local(service.recordingLink(session.id))]){const html=await(await fetch(url)).text();for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);if(url===manager)assert.match(html,/intro-upload/);if(url.includes('/recording/'))assert.ok(!html.includes('id="intro-upload"'));}
 }finally{await service?.close();await fs.rm(root,{recursive:true,force:true});}
});
test('browser reload reuses one track; distinct guests are capped and control characters are sanitized',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-guest-tracks-')),manager=new RecordingManager(root);let service;const sockets=[];
 try{const session=await manager.start({id:'guild',members:new Map()},'voice',connection());service=await DownloadService.create(root,'http://localhost');service.attach({},new SettingsStore(path.join(root,'settings.json')),manager);const port=await service.listen(0,'127.0.0.1'),base=service.browserLink(session.id).replace('http://localhost',`ws://127.0.0.1:${port}`);async function open(token,name='Guest'){const url=new URL(base);url.searchParams.set('guest',token);url.searchParams.set('name',name);const ws=new WebSocket(url);sockets.push(ws);await once(ws,'open');return ws;}async function close(ws){const closed=once(ws,'close');ws.close();await closed;await until(()=>service.guestCounts.size===0);}const token='a'.repeat(32),frame=Buffer.alloc(1924);frame.writeInt16LE(500,4);
 const first=await open(token,'Guest\u0001 name');first.send(frame);await until(()=>session.packets===1);await assert.rejects(open(token),/409/);await close(first);const again=await open(token);again.send(frame);await until(()=>session.packets===2);assert.equal(session.tracks.size,1);assert.equal([...session.tracks.values()][0].username,'Guest name');await close(again);
 for(let i=1;i<16;i++){const ws=await open(i.toString(16).padStart(32,'0'));ws.send(frame);await until(()=>session.packets===i+2);await close(ws);}assert.equal(session.tracks.size,16);await assert.rejects(open('b'.repeat(32)),/429/);assert.equal(session.state,'recording');await assert.rejects(open('not-a-token'),/400/);await assert.rejects(open(token,'\u0001'),/400/);
 }finally{for(const socket of sockets)if(socket.readyState===WebSocket.OPEN)socket.terminate();await service?.close();await manager.shutdown();await fs.rm(root,{recursive:true,force:true});}
});
test('reconnected browser PCM includes the gap without creating another file',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-guest-gap-'));try{const session=await RecordingSession.create(root,'guild','voice'),id=session.claimBrowserGuest('c'.repeat(32)),pcm=Buffer.alloc(3840,1),packet=Buffer.from([0xf8,0xff,0xfe]);await session.append(packet,id,'Guest',0,1n,pcm);await session.append(packet,id,'Guest',0,48001n,pcm,true);await session.close();const track=[...session.tracks.values()][0];assert.equal(session.tracks.size,1);const bytes=await fs.readFile(path.join(session.directory,track.pcmFile));assert.equal(bytes.length,48960*4);const info=await fs.stat(path.join(session.directory,track.pcmFile));assert.ok(info.blocks*512<info.size,'Reconnect silence should be sparse on the Linux test filesystem');assert.deepEqual(bytes.subarray(0,3840),pcm);assert.ok(bytes.subarray(3840,bytes.length-3840).every(byte=>byte===0));assert.deepEqual(bytes.subarray(-3840),pcm);}finally{await fs.rm(root,{recursive:true,force:true});}
});
test('XML projects strip forbidden controls while preserving legal whitespace and escaping',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-xml-controls-'));try{const {writeAudition}=require('../dist/exports/audition'),{writeAudacity}=require('../dist/exports/audacity');const wav=Buffer.alloc(48);wav.write('RIFF');wav.writeUInt32LE(40,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(2,22);wav.writeUInt32LE(48000,24);wav.writeUInt32LE(192000,28);wav.writeUInt16LE(4,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(4,40);await fs.writeFile(path.join(root,'track-1.wav'),wav);const tracks=[{file:'track-1.wav',username:'A\u0001&B\uFFFF'}],notes=[{seconds:0,text:'Note\u0002\tline\nnext'}];await writeAudition(root,tracks,notes);await writeAudacity(root,tracks,notes);for(const file of ['session.sesx','session.aup']){const xml=await fs.readFile(path.join(root,file),'utf8');assert.ok(!/[\x00-\x08\x0b\x0c\x0e-\x1f\uFFFF]/.test(xml));assert.match(xml,/A&amp;B/);const result=require('node:child_process').spawnSync('python3',['-c','import xml.etree.ElementTree as E,sys;E.parse(sys.argv[1])',path.join(root,file)],{encoding:'utf8'});assert.equal(result.status,0,result.stderr);}}finally{await fs.rm(root,{recursive:true,force:true});}
});
