const test=require('node:test'),assert=require('node:assert/strict'),{mkdtemp,writeFile,readFile,rm}=require('node:fs/promises'),path=require('node:path'),os=require('node:os');
const {uploadIntroChunk,getServerIntro}=require('../dist/exports/server-intro');
const {findSilenceCuts,cutSharedSilence,shiftedTime}=require('../dist/exports/silence');
function wav(seconds,soundAt=0){const frames=Math.round(seconds*48000),b=Buffer.alloc(44+frames*4);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(2,22);b.writeUInt32LE(48000,24);b.writeUInt32LE(192000,28);b.writeUInt16LE(4,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(frames*4,40);for(let i=Math.round(soundAt*48000);i<frames;i++){const v=Math.round(2000*Math.sin(i*2*Math.PI*440/48000));b.writeInt16LE(v,44+i*4);b.writeInt16LE(v,46+i*4);}return b;}
const ffmpeg=path.resolve(__dirname,'../bin/ffmpeg');
test('server intro uploads are reusable, isolated by server, and snapshotted for exports',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-intro-'));try{const bytes=wav(.2),result=await uploadIntroChunk(root,'server-a',{index:0,bytes:bytes.toString('base64'),final:true,name:'Theme.wav'});assert.equal(result.intro.name,'Theme.wav');assert.equal(result.intro.seconds,.2);assert.equal(await getServerIntro(root,'server-b'),undefined);const old=result.id;await uploadIntroChunk(root,'server-a',{index:0,bytes:wav(.3).toString('base64'),final:true,name:'Other.wav'});assert.equal((await getServerIntro(root,'server-a',old)).seconds,.2);assert.equal((await getServerIntro(root,'server-a')).seconds,.3);await assert.rejects(uploadIntroChunk(root,'server-a',{index:0,bytes:Buffer.from('playlist').toString('base64'),final:true}),/WAV/);}finally{await rm(root,{recursive:true,force:true});}});
test('shared silence trimming uses selected speakers, preserves sync, and shifts notes',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-silence-'));try{const a=path.join(root,'a.wav'),b=path.join(root,'b.wav');await writeFile(a,wav(32.5,32));await writeFile(b,wav(32.5,0));const all=await findSilenceCuts([a,b],new Set([a,b]),ffmpeg);assert.equal(all.cuts.length,0);const selected=await findSilenceCuts([a,b],new Set([a]),ffmpeg);assert.deepEqual(selected.cuts,[{start:0,end:32}]);assert.equal(shiftedTime(32.2,selected.cuts).toFixed(1),'0.2');await cutSharedSilence([a,b],selected.cuts,selected.duration,'pcm_s16le',ffmpeg);const remaining=await findSilenceCuts([a,b],new Set([a,b]),ffmpeg);assert.equal(remaining.duration,.5);assert.equal(remaining.cuts.length,0);}finally{await rm(root,{recursive:true,force:true});}});
test('intro export adds a separate intro track, delays speakers, and preserves their originals',async()=>{const {RecordingSession}=require('../dist/recording/session'),{OpusEncoder}=require('@discordjs/opus'),{exportSession}=require('../dist/exports/export');const root=await mkdtemp(path.join(os.tmpdir(),'witness-intro-export-'));try{const intro=await uploadIntroChunk(root,'guild',{index:0,bytes:wav(2).toString('base64'),final:true,name:'Intro.wav'}),session=await RecordingSession.create(root,'guild','voice'),encoder=new OpusEncoder(48000,2),pcm=Buffer.alloc(3840);for(let sample=0;sample<960;sample++){const value=Math.round(1000*Math.sin(sample*2*Math.PI*440/48000));pcm.writeInt16LE(value,sample*4);pcm.writeInt16LE(value,sample*4+2);}for(let i=0;i<150;i++)await session.append(encoder.encode(pcm),'speaker','Speaker',i*960,BigInt(i*960+1));await session.close();const baseline=await exportSession(root,session.id,{format:'flac'});const baselineAudio=await findSilenceCuts([path.join(baseline,'track-1.flac')],new Set(),ffmpeg);const dir=await exportSession(root,session.id,{format:'audition',trackFormat:'wav',mix:true,includeRaw:true,trimStart:.1,normalizeAudio:true,normalizeIntro:true,introID:intro.id});const manifest=JSON.parse(await readFile(path.join(dir,'manifest.json')));assert.equal(manifest.rawTracks.length,1);assert.equal(manifest.rawTracks[0].file,'raw-track-1.flac');const original=await findSilenceCuts([path.join(dir,'raw-track-1.flac')],new Set(),ffmpeg);assert.equal(original.duration,baselineAudio.duration);assert.deepEqual(await readFile(path.join(dir,"raw-track-1.flac")),await readFile(path.join(baseline,"track-1.flac")));const processed=await findSilenceCuts([path.join(dir,'track-1.wav')],new Set(),ffmpeg);assert.ok(processed.duration>original.duration,'Intro padding only affects processed audio');assert.ok((await readFile(path.join(dir,'project.zip'))).includes(Buffer.from('raw-track-1.flac')));assert.equal(manifest.tracks.length,2);assert.equal(manifest.tracks[1].userID,'server-intro');assert.equal(manifest.intro.seconds,2);assert.equal(manifest.normalizeAudio,true);assert.equal(manifest.normalizeIntro,true);const {measureLevel}=require('../dist/exports/normalization');const speaker=await measureLevel(path.join(dir,'track-1.wav'),ffmpeg),theme=await measureLevel(path.join(dir,'track-2.wav'),ffmpeg);assert.ok(Math.abs(speaker.lufs-theme.lufs)<1);const mixed=await measureLevel(path.join(dir,'mix.wav'),ffmpeg);assert.ok(Math.abs(mixed.lufs-theme.lufs)<1,'Intro is not attenuated as an extra speaker in the mixdown');assert.equal(JSON.parse(await readFile(path.join(session.directory,'session.json'))).tracks.length,1);assert.ok((await readFile(path.join(dir,'project.zip'))).includes(Buffer.from('track-2.wav')));}finally{await rm(root,{recursive:true,force:true});}});

test('silence duration is configurable and rejects invalid limits',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-threshold-'));try{const a=path.join(root,'a.wav');await writeFile(a,wav(3.5,3));assert.equal((await findSilenceCuts([a],new Set([a]),ffmpeg,undefined,4)).cuts.length,0);assert.deepEqual((await findSilenceCuts([a],new Set([a]),ffmpeg,undefined,1)).cuts,[{start:0,end:3}]);for(const value of [0,-1,NaN,Infinity,3601,'3'])await assert.rejects(findSilenceCuts([a],new Set([a]),ffmpeg,undefined,value),/Silence length/);}finally{await rm(root,{recursive:true,force:true});}});
test('a caller cannot overwrite an intro snapshot by reusing its ID for a new upload',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-intro-immutable-'));try{const first=await uploadIntroChunk(root,'guild',{index:0,bytes:wav(.2).toString('base64'),final:true,name:'Original'});const {introPCM}=require('../dist/exports/server-intro'),file=introPCM(root,'guild',first.id),before=await readFile(file);await assert.rejects(uploadIntroChunk(root,'guild',{id:first.id,index:0,bytes:wav(.3).toString('base64'),final:true,name:'Replacement'}));const after=await readFile(file);assert.equal(after.length,before.length,'A rejected upload must not overwrite the selected intro PCM');assert.deepEqual(after,before);assert.equal((await getServerIntro(root,'guild',first.id)).name,'Original');}finally{await rm(root,{recursive:true,force:true});}
});
