const test=require('node:test'),assert=require('node:assert/strict');const {mkdtemp,rm}=require('node:fs/promises');const os=require('node:os'),path=require('node:path');const {RecordingSession}=require('../dist/recording/session');const {RecordingPanels,panelBody}=require('../dist/discord/panel');
test('one compact panel is created for concurrent starts and edited through reconnect and stop',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-panel-'));let panels,session;
 try{session=await RecordingSession.create(root,'guild','voice');await session.setTitle('Campaign');const messages=[],edits=[];panels=new RecordingPanels({createMessage:async(channel,body)=>{messages.push({channel,body});await new Promise(r=>setTimeout(r,5));return{id:'message'};},editMessage:async(channel,id,body)=>edits.push({channel,id,body})},{status:{low:false}});
 await Promise.all([panels.ensure('text',session),panels.ensure('text',session)]);assert.equal(messages.length,1);assert.equal(messages[0].body.components[0].components.length,3);assert.deepEqual(messages[0].body.allowedMentions,{parse:[]});session.voiceState='reconnecting';await panels.update();assert.ok(edits.at(-1).body.content.includes('Reconnecting'));session.voiceState='connected';await session.close();await panels.update();assert.equal(edits.at(-1).id,'message');assert.ok(edits.at(-1).body.content.includes('Recording saved'));assert.ok(edits.at(-1).body.components[0].components.every(button=>button.disabled));
 const next=await RecordingSession.create(root,'guild','voice');await panels.ensure('text',next);assert.equal(messages.length,2);await next.close();await panels.close();
 }finally{await session?.close();await panels?.close();await rm(root,{recursive:true,force:true});}
});
test('panel shows storage and recovery warnings; button identities remain session-scoped',()=>{
 const session={id:'session',title:'Title',startedAt:'2026-10-01T00:00:00Z',state:'failed',voiceState:'connected',tracks:new Map([['one',{}]]),notes:2,packetStats:{duplicatesDropped:3,latePacketsDropped:4}};const body=panelBody(session,true,Date.parse('2026-10-01T00:01:00Z'));assert.ok(body.content.includes('preserved for recovery'));assert.ok(body.content.includes('Low disk space'));assert.ok(body.content.includes('1m 00s'));assert.ok(body.components[0].components.every(button=>button.custom_id.endsWith(':session')&&button.disabled));
});
test('non-owner server members can add notes using the slash command and panel modal',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-member-note-'));process.env.DISCORD_TOKEN='offline-test-token';process.env.RECORDING_PATH=root;
 const {EventEmitter}=require('node:events');const {createDiscordClient,recordings,closeRecordingPanels}=require('../dist/discord/client');
 try{const client=createDiscordClient(),guild={id:'guild',members:new Map(),channels:new Map()};client.guilds.set(guild.id,guild);const voice=new EventEmitter(),receiver=new EventEmitter();voice.receive=()=>receiver;voice.disconnect=()=>{};const session=await recordings.start(guild,'voice',voice);
 async function dispatch(type,data,member){let resolve,reject;const completion=new Promise((yes,no)=>{resolve=yes;reject=no;});const interaction={type,data,guildID:guild.id,member:{id:member},acknowledged:false,defer:async()=>{interaction.acknowledged=true;},createMessage:async body=>resolve(body),editOriginalMessage:async body=>resolve(body)};client.emit('interactionCreate',interaction);let timer;try{return await Promise.race([completion,new Promise((_,no)=>timer=setTimeout(()=>no(Error('Interaction timed out')),2000))]);}finally{clearTimeout(timer);}}
 const slash=await dispatch(2,{name:'note',options:[{name:'text',value:'DM note'}]},'dm-member');assert.ok(slash.content.includes('Note saved'));const modal=await dispatch(5,{custom_id:`witness:note-submit:${session.id}`,components:[{components:[{custom_id:'note',value:'Player note'}]}]},'player-member');assert.ok(modal.content.includes('note saved'));await recordings.stop(guild.id);const {readFile}=require('node:fs/promises'),notes=(await readFile(path.join(session.directory,'notes.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);assert.deepEqual(notes.map(note=>note.authorID),['dm-member','player-member']);assert.deepEqual(notes.map(note=>note.text),['DM note','Player note']);
 }finally{await recordings.shutdown();await closeRecordingPanels();await rm(root,{recursive:true,force:true});}
});
