const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),{EventEmitter}=require('node:events');
const until=async check=>{for(let i=0;i<400;i++){if(check())return;await new Promise(resolve=>setTimeout(resolve,10));}throw Error('Timeout');};
test('every new Discord start path plays once; repeats, reconnect and stop do not; self audio is excluded',async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'witness-start-paths-'));process.env.DISCORD_TOKEN='offline-test-token';process.env.RECORDING_PATH=root;delete process.env.START_SOUND;
 const scheduleModule=require('../dist/automation/schedules'),Original=scheduleModule.ScheduleRunner;let schedule;scheduleModule.ScheduleRunner=class extends Original{constructor(...args){super(...args);schedule=this;}};
 const {createDiscordClient,recordings,settingsStore,closeRecordingPanels}=require('../dist/discord/client');let client;const plays=[],connections=[];let speak=true;
 try{await settingsStore.load();client=createDiscordClient();client.user={id:'bot',username:'Witness'};client.createMessage=async()=>({id:'panel'});client.editMessage=async()=>({});const guild={id:'123',name:'Guild',shard:{ready:true},members:new Map([['user',{id:'user',username:'User',bot:false}]]),channels:new Map()},channel={id:'456',type:2,name:'Voice',guild,voiceMembers:{some:()=>true},permissionsOf:()=>({has:permission=>permission!=='voiceSpeak'||speak}),leave:()=>client.voiceConnections.delete(guild.id)};guild.channels.set(channel.id,channel);client.guilds.set(guild.id,guild);
 client.joinVoiceChannel=async()=>{const connection=new EventEmitter(),receiver=new EventEmitter();connection.receive=()=>receiver;connection.receiver=receiver;connection.play=(file,options)=>{plays.push({file,options});connection.emit('end');};connection.disconnect=()=>{};connections.push(connection);client.voiceConnections.set(guild.id,connection);return connection;};
 async function command(name,options=[],manager=true){let done,timer;const response=new Promise(resolve=>done=resolve);client.emit('interactionCreate',{type:2,data:{name,options},guildID:guild.id,member:{id:'user',roles:[],permissions:{has:()=>manager}},channel:{id:'text'},defer:async()=>{},createMessage:async body=>done(body),editOriginalMessage:async body=>done(body)});try{return await Promise.race([response,new Promise((_,reject)=>timer=setTimeout(()=>reject(Error('Command timeout')),4000))]);}finally{clearTimeout(timer);}}
 const start=()=>command('record',[{name:'channel',value:channel.id}]);await start();await until(()=>plays.length===1);const first=recordings.sessions.get(guild.id);await start();assert.equal(plays.length,1);assert.equal(recordings.sessions.get(guild.id),first);
 const voice=connections[0];voice.receiver.emit('data',Buffer.from([0xf8,0xff,0xfe]),'bot',0);voice.receiver.emit('data',Buffer.from([0xf8,0xff,0xfe]),'user',0);recordings.retryDelays=[0];voice.emit('disconnect',Error('Network lost'));await until(()=>connections.length>=3&&first.voiceState==='connected');assert.equal(plays.length,1);await recordings.stop(guild.id);client.voiceConnections.delete(guild.id);assert.equal(plays.length,1);assert.ok(![...first.tracks.values()].some(track=>track.id==='bot'));assert.ok([...first.tracks.values()].some(track=>track.id==='user'));
 await settingsStore.update(guild.id,{autoJoin:true,autoRecord:true});client.emit('voiceChannelJoin',{id:'user',username:'User',bot:false,roles:[]},channel);await until(()=>plays.length===2);await recordings.stop(guild.id);client.voiceConnections.delete(guild.id);await settingsStore.update(guild.id,{autoJoin:false,autoRecord:false,eventRecordings:[{eventID:'789',stopOnEnd:false}]});client.emit('guildScheduledEventUpdate',{id:'789',guild,channel,entityType:2,status:2,name:'Game'});await until(()=>plays.length===3);await recordings.stop(guild.id);client.voiceConnections.delete(guild.id);
 const rule=scheduleModule.newSchedule({channelID:channel.id,title:'Scheduled game',days:[1],time:'19:00',timezone:'America/New_York',durationMinutes:60});await settingsStore.update(guild.id,{schedules:[rule]});await schedule.load();await schedule.tick(new Date('2026-10-05T23:00:00Z'));await until(()=>plays.length===4);await recordings.stop(guild.id);client.voiceConnections.delete(guild.id);
 assert.match((await command('startsound',[{name:'mode',value:'off'}],false)).content,/Manage Server/);assert.match((await command('startsound',[{name:'mode',value:'status'}],false)).content,/default/);assert.match((await command('startsound',[{name:'mode',value:'custom'}])).content,/Upload/);assert.match((await command('startsound',[{name:'mode',value:'off'}])).content,/Participants will rely/);await start();await new Promise(resolve=>setTimeout(resolve,20));assert.equal(plays.length,4);assert.equal(recordings.sessions.get(guild.id).state,'recording');await recordings.stop(guild.id);client.voiceConnections.delete(guild.id);await command('startsound',[{name:'mode',value:'default'}]);speak=false;await start();await new Promise(resolve=>setTimeout(resolve,20));assert.equal(plays.length,4);assert.equal(recordings.sessions.get(guild.id).state,'recording');await recordings.stop(guild.id);client.voiceConnections.delete(guild.id);
 await settingsStore.update(guild.id,{restrictAccess:true,accessRoleID:'999'});assert.match((await command('startsound',[{name:'mode',value:'status'}],false)).content,/default/);
 }finally{scheduleModule.ScheduleRunner=Original;await recordings.shutdown();await closeRecordingPanels();await fs.rm(root,{recursive:true,force:true});}
});
