const test=require('node:test'),assert=require('node:assert/strict');
const {mkdtemp,rm,readFile}=require('node:fs/promises');const path=require('node:path'),os=require('node:os');
const {RecordingSession}=require('../dist/recording/session');const {SessionSync,validateSync}=require('../dist/recording/sync');const {SettingsStore}=require('../dist/storage/settings');const {DownloadService}=require('../dist/downloads/service');const {exportSession}=require('../dist/exports/export');
test('sync settings validate, persist and default to disabled',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-sync-settings-'));try{const store=new SettingsStore(path.join(root,'settings.json'));assert.equal(store.get('123').sync,undefined);const sync={enabled:true,mode:'both',startDelay:3,endDelay:5};await store.update('123',{sync});const copy=new SettingsStore(path.join(root,'settings.json'));await copy.load();assert.deepEqual(copy.get('123').sync,sync);for(const change of [{startDelay:0},{endDelay:NaN},{mode:'unknown'},{enabled:'yes'}])assert.throws(()=>validateSync({...sync,...change}));}finally{await rm(root,{recursive:true,force:true});}
});
test('start/end cues share IDs across stored markers and exports, with origin and intro-independent timing',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-sync-'));try{const session=await RecordingSession.create(root,'123','voice');const slate=new SessionSync(session,{enabled:true,mode:'both',startDelay:0.01,endDelay:0.01});slate.start();await new Promise(r=>setTimeout(r,400));await slate.stop();await session.close();assert.equal(slate.cues.length,2);assert.ok(slate.cues.every(c=>c.state==='captured'));const saved=JSON.parse(await readFile(path.join(session.directory,'sync-cues.json')));assert.deepEqual(saved.cues.map(c=>c.id),slate.cues.map(c=>c.id));const metadata=JSON.parse(await readFile(path.join(session.directory,'session.json')));assert.equal(metadata.tracks[0].username,'Sync cues');assert.equal(metadata.packets,30);const notes=(await readFile(path.join(session.directory,'notes.jsonl'),'utf8')).trim().split('\n').map(JSON.parse);assert.equal(notes.length,2);assert.equal(notes[0].seconds,slate.cues[0].seconds);assert.ok(notes[1].text.includes(slate.cues[1].id));const directory=await exportSession(root,session.id,{format:'audition',trackFormat:'wav'});const manifest=JSON.parse(await readFile(path.join(directory,'manifest.json')));assert.equal(manifest.syncCues.cues.length,2);assert.equal(manifest.syncCues.cues[0].originalAudioSeconds,0);assert.equal(manifest.syncCues.cues[0].exportSeconds,0);const zip=await readFile(path.join(directory,'project.zip'));assert.ok(zip.includes(Buffer.from(slate.cues[0].id)));}finally{await rm(root,{recursive:true,force:true});}
});
test('stopping before a delayed start cancels it and error stop does not add an end cue',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-sync-cancel-'));try{const session=await RecordingSession.create(root,'123','voice');const slate=new SessionSync(session,{enabled:true,mode:'both',startDelay:3,endDelay:3});slate.start();await slate.stop(false);await slate.stop(false);await session.close();assert.equal(slate.cues.length,1);assert.equal(slate.cues[0].state,'cancelled');assert.equal(session.packets,0);}finally{await rm(root,{recursive:true,force:true});}});
test('sync feed requires a scoped signature and exposes cue timing without recordings or server settings',async()=>{
 const root=await mkdtemp(path.join(os.tmpdir(),'witness-sync-feed-'));let service;try{const settings=new SettingsStore(path.join(root,'settings.json'));service=await DownloadService.create(root,'https://example.com');service.attach({},settings,{syncSessions:new Map([['123',{cues:[{id:'cue',targetUTC:Date.now()+3000}]}]])});const port=await service.listen(0,'127.0.0.1'),local=u=>u.replace('https://example.com',`http://127.0.0.1:${port}`);const dashboard=await(await fetch(local(service.dashboardLink('123')),{headers:{Accept:'application/json'}})).json();const url=local(dashboard.syncFeedURL);const data=await(await fetch(url)).json();assert.equal(data.version,1);assert.equal(data.cues.length,1);assert.equal(data.settings,undefined);assert.equal(data.sessions,undefined);assert.equal((await fetch(`http://127.0.0.1:${port}/sync-feed/123`)).status,403);assert.equal((await fetch(url.replace('/123?','/456?'))).status,403);assert.equal((await fetch(url,{method:'POST'})).status,405);}finally{await service?.close();await rm(root,{recursive:true,force:true});}
});
test('recording manager automatically runs the end cue before closing and default recordings remain unchanged',async()=>{
 const {RecordingManager}=require('../dist/recording/manager');const {EventEmitter}=require('node:events');const root=await mkdtemp(path.join(os.tmpdir(),'witness-sync-manager-'));
 try{const connection=new EventEmitter();connection.receive=()=>new EventEmitter();const guild={id:'123',channels:new Map(),members:new Map()};const manager=new RecordingManager(root,[],{get:()=>({sync:{enabled:true,mode:'end',startDelay:3,endDelay:3}})});const session=await manager.start(guild,'voice',connection);assert.equal(manager.syncSessions.get('123').cues.length,0);const stopping=manager.stop('123');await new Promise(r=>setTimeout(r,50));assert.equal(session.state,'recording');assert.equal(manager.syncSessions.get('123').cues[0].kind,'end');await stopping;assert.equal(session.state,'completed');assert.equal(session.packets,15);assert.equal(manager.sessions.size,0);
 }finally{await rm(root,{recursive:true,force:true});}
});

test('Stop during a started cue lets its audio and marker finish together',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'witness-sync-stop-'));try{const session=await RecordingSession.create(root,'123','voice');const slate=new SessionSync(session,{enabled:true,mode:'start',startDelay:0.01,endDelay:0.01});slate.start();await new Promise(r=>setTimeout(r,80));await slate.stop();await session.close();assert.equal(slate.cues[0].state,'captured');assert.equal(session.packets,15);assert.equal(session.notes,1);}finally{await rm(root,{recursive:true,force:true});}});
